name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fix permissions
        run: |
          chmod -c -R +rX "_site/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: src/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}

    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          preview: ${{ !(github.event_name == 'push' && github.ref_name == 'main') }}

  comment-on-push:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Comment on PR
        uses: actions/github-script@v4

        env:
          COMMIT_COMMENT: |
            # ✅ GitHub Pages Deployed

            Preview URL: ${{ needs.deploy.outputs.page_url }}

            ---

            <details>
              <summary>🚀 Deployment Details</summary>

              GitHub Action Run: <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">${{ github.run_id }}</a>

              Source: <a href="https://github.com/${{ github.repository }}/tree/${{github.sha}}">${{github.sha}}</a>

            </details>

        with:
          github-token: ${{ secrets.GH_BOT_TOKEN }}
          script: |
            await github.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: process.env.COMMIT_COMMENT
            });


